name: Deploy Laravel app with Deployer to staging server

on:
  push:
    branches:
      - dev

concurrency:
  group: cd-staging
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v5

      - name: Deploy
        uses: deployphp/action@v1
        with:
          dep: "deploy staging"
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          deployer-version: v7.5.12

      - name: Maintenance
        uses: deployphp/action@v1
        with:
          dep: "run 'php artisan down --secret=${{ secrets.MAINTENANCE_KEY }}' staging"
          deployer-version: v7.5.12
