name: Deploy Laravel with Deployer

on:
  push:
    branches:
      - dev
      - main

concurrency:
  group: cd-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Install dependencies
        run: composer install

      - name: Deploy
        uses: deployphp/action@v1
        with:
          dep: "deploy production"
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
